[package]
name = "markdown_parser"
version = "0.1.0"
authors = ["Travis Haley <thaley@dlr360.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.11"
